project:
  type: book

book:
  title: "Algorithms & Data Structures SoSe 25 Notes"
  author: "Igor Dimitrov"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - part: "Python"
      chapters: 
        - python/iterables.qmd
    - part: "Exam"
      chapters:
        - exam/2024.qmd
  downloads: ["pdf"]
  page-navigation: true

bibliography: references.bib

number-depth: 1

csl: nature.csl

format:
  html:
    theme: cosmo
    toc-depth: 2
  pdf:
    documentclass: scrreprt
    number-depth: 1



